In [37]:
import pandas as pd

In [2]:
groceries = pd.Series(data=[30, 5, 'Yes', 'No'], index=['eggs', 'apples', 'milk', 'bread'])

print(groceries)

eggs       30
apples      5
milk      Yes
bread      No
dtype: object

In [4]:
print(groceries.shape)

(4,)

In [5]:
groceries.ndim

1

In [6]:
groceries.size

4

In [7]:
groceries.index

Index(['eggs', 'apples', 'milk', 'bread'], dtype='str')

In [8]:
groceries.values

array([30, 5, 'Yes', 'No'], dtype=object)

In [9]:
'banana' in groceries

False

In [10]:
'bread' in groceries

True

In [11]:
groceries['eggs']

30

In [12]:
groceries[['milk', 'bread']]

milk     Yes
bread     No
dtype: object

In [14]:
groceries.iloc[0]

30

In [15]:
groceries.iloc[-1]

'No'

In [16]:
groceries.iloc[[1,2]]

apples      5
milk      Yes
dtype: object

In [17]:
groceries.loc[['eggs', 'apples']]

eggs      30
apples     5
dtype: object

In [18]:
groceries['eggs'] = 2
groceries

eggs        2
apples      5
milk      Yes
bread      No
dtype: object

In [20]:
groceries.drop('apples')

eggs       2
milk     Yes
bread     No
dtype: object

In [21]:
groceries

eggs        2
apples      5
milk      Yes
bread      No
dtype: object

In [22]:
groceries.drop('apples', inplace=True)
groceries

eggs       2
milk     Yes
bread     No
dtype: object

In [24]:
fruits = pd.Series(
    [10, 6, 6],
    ['apples', 'oranges', 'bananas']
)

fruits

apples     10
oranges     6
bananas     6
dtype: int64

In [25]:
fruits + 2

apples     12
oranges     8
bananas     8
dtype: int64

In [26]:
fruits - 3

apples     7
oranges    3
bananas    3
dtype: int64

In [27]:
fruits * 3

apples     30
oranges    18
bananas    18
dtype: int64

In [28]:
fruits / 2

apples     5.0
oranges    3.0
bananas    3.0
dtype: float64

In [29]:
import numpy as np

In [30]:
np.sqrt(fruits)

apples     3.162278
oranges    2.449490
bananas    2.449490
dtype: float64

In [31]:
np.power(fruits, 2)

apples     100
oranges     36
bananas     36
dtype: int64

In [32]:
fruits['apples'] + 2

np.int64(12)

In [33]:
fruits.iloc[0] - 2

np.int64(8)

In [34]:
fruits[['apples', 'oranges']] * 2

apples     20
oranges    12
dtype: int64

In [35]:
fruits.loc[['apples', 'oranges']] / 2

apples     5.0
oranges    3.0
dtype: float64

In [38]:
items = {
    'Alice': pd.Series([40, 20, 40], index=['books', 'glasses', 'bike']),
    'Bob': pd.Series([245, 543, 23, 43], index=['bike', 'pants', 'watch', 'books'])
}

type(items)

dict

In [39]:
shopping_carts = pd.DataFrame(items)

shopping_carts

         Alice    Bob
bike      40.0  245.0
books     40.0   43.0
glasses   20.0    NaN
pants      NaN  543.0
watch      NaN   23.0

In [40]:
data = {
    'Alice': pd.Series([40, 20, 40]),
    'Bob': pd.Series([245, 543, 23, 43])
}

df = pd.DataFrame(data)

df

   Alice  Bob
0   40.0  245
1   20.0  543
2   40.0   23
3    NaN   43

In [41]:
shopping_carts.index

Index(['bike', 'books', 'glasses', 'pants', 'watch'], dtype='str')

In [42]:
shopping_carts.columns

Index(['Alice', 'Bob'], dtype='str')

In [43]:
shopping_carts.values

array([[ 40., 245.],
       [ 40.,  43.],
       [ 20.,  nan],
       [ nan, 543.],
       [ nan,  23.]])

In [44]:
shopping_carts.shape

(5, 2)

In [45]:
shopping_carts.ndim

2

In [46]:
shopping_carts.size

10

In [47]:
bob_sc = pd.DataFrame(items, columns=['Bob'])

bob_sc

       Bob
bike   245
pants  543
watch   23
books   43

In [50]:
sel_sc = pd.DataFrame(items, index=['books', 'pants'])

sel_sc

       Alice  Bob
books   40.0   43
pants    NaN  543

In [51]:
data = pd.DataFrame({
    'Alice': [1, 2, 3],
    'Bob': [4, 5, 6],
})

data

   Alice  Bob
0      1    4
1      2    5
2      3    6

In [52]:
data = pd.DataFrame({
    'Alice': [1, 2, 3],
    'Bob': [4, 5, 6],
}, index=['one', 'two', 'three'])

data

       Alice  Bob
one        1    4
two        2    5
three      3    6

In [53]:
items = [{'bikes': 20, 'pants': 30, 'watches': 35}, 
          {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5}]
store_items = pd.DataFrame(items, index = ['store 1', 'store 2'])

store_items

         bikes  pants  watches  glasses
store 1     20     30       35      NaN
store 2     15      5       10     50.0

In [54]:
store_items[['bikes']]

         bikes
store 1     20
store 2     15

In [56]:
store_items[['bikes', 'watches']]

         bikes  watches
store 1     20       35
store 2     15       10

In [57]:
store_items.loc[['store 1']]

         bikes  pants  watches  glasses
store 1     20     30       35      NaN

In [58]:
store_items['bikes']['store 1']

np.int64(20)

In [59]:
store_items['shirt'] = [15, 2]

In [60]:
store_items

         bikes  pants  watches  glasses  shirt
store 1     20     30       35      NaN     15
store 2     15      5       10     50.0      2

In [61]:
store_items['suits'] = store_items['shirt'] + store_items['pants']

In [62]:
store_items

         bikes  pants  watches  glasses  shirt  suits
store 1     20     30       35      NaN     15     45
store 2     15      5       10     50.0      2      7

In [64]:
new_items = [
    {
        'bikes': 20,
        'pants': 30,
        'watches': 35,
        'glasses': 41,
    }
]

new_store = pd.DataFrame(new_items, index=['store 3'])

In [66]:
store_items = pd.concat([store_items, new_store])

store_items

         bikes  pants  watches  glasses  shirt  suits
store 1     20     30       35      NaN   15.0   45.0
store 2     15      5       10     50.0    2.0    7.0
store 3     20     30       35     41.0    NaN    NaN

In [67]:
store_items['new_watches'] = store_items['watches'][1:]

In [68]:
store_items

         bikes  pants  watches  glasses  shirt  suits  new_watches
store 1     20     30       35      NaN   15.0   45.0          NaN
store 2     15      5       10     50.0    2.0    7.0         10.0
store 3     20     30       35     41.0    NaN    NaN         35.0

In [69]:
store_items.insert(5, 'shoes', [6, 5, 0])

store_items

         bikes  pants  watches  glasses  shirt  shoes  suits  new_watches
store 1     20     30       35      NaN   15.0      6   45.0          NaN
store 2     15      5       10     50.0    2.0      5    7.0         10.0
store 3     20     30       35     41.0    NaN      0    NaN         35.0

In [70]:
store_items.pop('new_watches')
store_items

         bikes  pants  watches  glasses  shirt  shoes  suits
store 1     20     30       35      NaN   15.0      6   45.0
store 2     15      5       10     50.0    2.0      5    7.0
store 3     20     30       35     41.0    NaN      0    NaN

In [71]:
store_items = store_items.drop(['watches', 'shoes'], axis=1)

In [72]:
store_items

         bikes  pants  glasses  shirt  suits
store 1     20     30      NaN   15.0   45.0
store 2     15      5     50.0    2.0    7.0
store 3     20     30     41.0    NaN    NaN

In [73]:
store_items = store_items.drop(['store 1', 'store 2'], axis=0)

store_items

         bikes  pants  glasses  shirt  suits
store 3     20     30     41.0    NaN    NaN

In [74]:
store_items = store_items.rename(columns={'bikes': 'hats'})
store_items

         hats  pants  glasses  shirt  suits
store 3    20     30     41.0    NaN    NaN

In [75]:
store_items = store_items.rename(index={'store 3': 'last store'})

store_items

            hats  pants  glasses  shirt  suits
last store    20     30     41.0    NaN    NaN

In [76]:
store_items = store_items.set_index('pants')

store_items

       hats  glasses  shirt  suits
pants
30       20     41.0    NaN    NaN

In [77]:
# We create a list of Python dictionaries
items2 = [{'bikes': 20, 'pants': 30, 'watches': 35, 'shirts': 15, 'shoes':8, 'suits':45},
          {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5, 'shirts': 2, 'shoes':5, 'suits':7},
          {'bikes': 20, 'pants': 30, 'watches': 35, 'glasses': 4, 'shoes':10}]

# We create a DataFrame  and provide the row index
store_items = pd.DataFrame(items2, index = ['store 1', 'store 2', 'store 3'])

# We display the DataFrame
print(store_items)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     NaN     10    NaN      4.0

In [78]:
x = store_items.isnull().sum().sum()
x

np.int64(3)

In [79]:
store_items.isnull()

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1  False  False    False   False  False  False     True
store 2  False  False    False   False  False  False    False
store 3  False  False    False    True  False   True    False

In [80]:
store_items.count()

bikes      3
pants      3
watches    3
shirts     2
shoes      3
suits      2
glasses    2
dtype: int64

In [81]:
store_items.dropna(axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 2     15      5       10     2.0      5    7.0     50.0

In [82]:
store_items.dropna(axis=1)

         bikes  pants  watches  shoes
store 1     20     30       35      8
store 2     15      5       10      5
store 3     20     30       35     10

In [83]:
store_items.fillna(0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      0.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     0.0     10    0.0      4.0

In [84]:
store_items.ffill(axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     2.0     10    7.0      4.0

In [85]:
store_items.ffill(axis=1)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0     45.0
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    35.0   10.0   10.0      4.0

In [86]:
store_items.bfill(axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0     50.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     NaN     10    NaN      4.0

In [87]:
store_items.bfill(axis=1)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0      NaN
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    10.0   10.0    4.0      4.0

In [88]:
store_items.interpolate(method='linear', axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     2.0     10    7.0      4.0

In [89]:
store_items.interpolate(method='linear', axis=1)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0     45.0
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    22.5   10.0    7.0      4.0