In [1]:
!python --version

Python 3.14.3

In [ ]:
from datasets import load_dataset
import pandas as pd
from huggingface_hub import HfFileSystem
import json

fs = HfFileSystem()

reviews = []

with fs.open("datasets/McAuley-Lab/Amazon-Reviews-2023/raw/review_categories/Electronics.jsonl", "r") as f:
    for i, line in enumerate(f):
        if i >= 100:
            break
        reviews.append(json.loads(line))

reviews_df = pd.DataFrame(reviews)
reviews_df

    rating  ... verified_purchase
0      3.0  ...              True
1      1.0  ...              True
2      5.0  ...              True
3      5.0  ...              True
4      5.0  ...              True
..     ...  ...               ...
95     5.0  ...              True
96     5.0  ...              True
97     5.0  ...              True
98     5.0  ...              True
99     4.0  ...              True

[100 rows x 10 columns]

In [6]:
reviews_df.head()

   rating  ... verified_purchase
0     3.0  ...              True
1     1.0  ...              True
2     5.0  ...              True
3     5.0  ...              True
4     5.0  ...              True

[5 rows x 10 columns]

In [9]:
Items_to_print = 10

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 50)

print(reviews_df.head(10))

   rating                                        title                                               text                                             images        asin parent_asin                       user_id      timestamp  helpful_vote  verified_purchase
0     3.0            Smells like gasoline! Going back!  First & most offensive: they reek of gasoline ...  [{'small_image_url': 'https://m.media-amazon.c...  B083NRGZMM  B083NRGZMM  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1658185117948             0               True
1     1.0      Didn’t work at all lenses loose/broken.  These didn’t work. Idk if they were damaged in...                                                 []  B07N69T6TM  B07N69T6TM  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1592678549731             0               True
2     5.0                                   Excellent!  I love these. They even come with a carry case...                                                 []  B01G8JO5F2  B01G8JO5F2  AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  1523093017534             0               True
3     5.0                       Great laptop backpack!  I was searching for a sturdy backpack for scho...                                                 []  B001OC5JKY  B001OC5JKY  AGGZ357AO26RQZVRLGU4D4N52DZQ  1290278495000            18               True
4     5.0  Best Headphones in the Fifties price range!  I've bought these headphones three times becau...                                                 []  B013J7WUGC  B07CJYMRWM  AG2L7H23R5LLKDKLBEF2Q3L2MVDA  1676601581238             0               True
5     5.0                        Great Fan! I’m a FAN!  Light weight, quiet and totally awesome!!! It ...                                                 []  B072DSHKCH  B07CML419K  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1637522881041             0               True
6     5.0                    solid sound for the price  Update 2-they sent a new warranty replacement....                                                 []  B07BHHB5RH  B07BHHB5RH  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1565130879386             0               True
7     5.0            Love the headphones - great range  These are fantastic headphones and I love that...                                                 []  B07BND376H  B09S6Y5BRG  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1541356831659             9               True
8     5.0                                   Five Stars                         pretty good for the price.                                                 []  B002HWRZ2K  B01LW71IBJ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1456772571000             0               True
9     5.0                               BUY THIS THANG  yes.. so good.  just buy it. my favorite featu...                                                 []  B00WK47VEW  B017T99JPG  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  1456772365000             0               True

In [11]:
metadata = []

with fs.open("datasets/McAuley-Lab/Amazon-Reviews-2023/raw/meta_categories/meta_Electronics.jsonl", "r") as f:
    for i, meta in enumerate(f):
        if i >= 100:
            break
        metadata.append(json.loads(meta))
item_metadata_df = pd.DataFrame(metadata)
item_metadata_df

                main_category                                              title  average_rating  rating_number                                           features                                        description   price                                             images                                             videos                                       store                                         categories                                            details parent_asin bought_together
0             All Electronics             FS-1051 FATSHARK TELEPORTER V3 HEADSET             3.5              6                                                 []  [Teleporter V3 The “Teleporter V3” kit sets a ...     NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                   Fat Shark   [Electronics, Television & Video, Video Glasses]  {'Date First Available': 'August 2, 2014', 'Ma...  B00MCW7G9M            None
1             All Electronics                      Ce-H22B12-S1 4Kx2K Hdmi 4Port             5.0              1             [UPC: 662774021904, Weight: 0.600 lbs]                               [HDMI In - HDMI Out]     NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                        SIIG  [Electronics, Television & Video, Accessories,...  {'Product Dimensions': '0.83 x 4.17 x 2.05 inc...  B00YT6XQSE            None
2                   Computers  Digi-Tatoo Decal Skin Compatible With MacBook ...             4.5            246  [WARNING: Please IDENTIFY MODEL NUMBER on the ...                                                 []   19.99  [{'thumb': 'https://m.media-amazon.com/images/...  [{'title': 'AL 2Sides Video', 'url': 'https://...                                  Digi-Tatoo  [Electronics, Computers & Accessories, Laptop ...  {'Brand': 'Digi-Tatoo', 'Color': 'Fresh Marble...  B07SM135LS            None
3              AMAZON FASHION  NotoCity Compatible with Vivoactive 4 band 22m...             4.5            233  [☛NotoCity 22mm band is designed for Vivoactiv...                                                 []    9.99  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                    NotoCity  [Electronics, Wearable Technology, Clips, Arm ...  {'Date First Available': 'May 29, 2020', 'Manu...  B089CNGZCW            None
4   Cell Phones & Accessories             Motorola Droid X Essentials Combo Pack             3.8             64  [New Droid X Essentials Combo Pack, Exclusive ...  [all Genuine High Quality Motorola Made Access...   14.99  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                     Verizon  [Electronics, Computers & Accessories, Compute...  {'Product Dimensions': '11.6 x 6.9 x 3.1 inche...  B004E2Z88O            None
..                        ...                                                ...             ...            ...                                                ...                                                ...     ...                                                ...                                                ...                                         ...                                                ...                                                ...         ...             ...
95            All Electronics  LaCie Rugged All-Terrain Safe 500 GB USB 2.0/F...             3.2             18  [Biometric authentication: up to ten users, 12...  [Product Description, The LaCie Rugged Safe is...  146.99  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                       LaCie  [Electronics, Computers & Accessories, Data St...  {'Product Dimensions': '5.7 x 3.5 x 1 inches',...  B003XT6OTG            None
96            Car Electronics  SSV Works Polaris Ranger XP9 900 2012-up and F...             5.0              1                                              [New]  [Fitment: (2015+) Polaris Ranger, (2013+) Rang...     NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                   SSV Works  [Electronics, Car & Vehicle Electronics, Car E...  {'Item Weight': '5 pounds', 'Package Dimension...  B00O2IZZC4            None
97    Industrial & Scientific  Monsoon G1/4" to 1/2" ID, 3/4" OD Chain Gun Co...             5.0              1                                                 []                                                 []   25.71  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                     Monsoon  [Electronics, Computers & Accessories, Compute...  {'Item Dimensions LxWxH': '3.94 x 1.97 x 1.97 ...  B00M9AEJQA            None
98             Camera & Photo  YEELE 6x4ft Galaxy Backdrop Purple Night Sky i...             4.8             19                                                 []                                                 []     NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []                                       Yeele  [Electronics, Camera & Photo, Lighting & Studi...  {'Package Dimensions': '14 x 13 x 0.6 inches',...  B07XCWMSSY            None
99                  Computers  Aruba Instant On AP11 2x2 WiFi Access Point | ...             4.4            119  [Aruba Instant On AP11 Indoor Access Points de...                                                 []  109.99  [{'thumb': 'https://m.media-amazon.com/images/...  [{'title': 'What is a Wireless Access Point?',...  Aruba a Hewlett Packard Enterprise company  [Electronics, Computers & Accessories, Network...  {'Product Dimensions': '5.98 x 5.98 x 1.34 inc...  B098ZFMY25            None

[100 rows x 14 columns]

In [12]:
print(item_metadata_df.head(10))

               main_category                                              title  average_rating  rating_number                                           features                                        description  price                                             images                                             videos            store                                         categories                                            details parent_asin bought_together
0            All Electronics             FS-1051 FATSHARK TELEPORTER V3 HEADSET             3.5              6                                                 []  [Teleporter V3 The “Teleporter V3” kit sets a ...    NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []        Fat Shark   [Electronics, Television & Video, Video Glasses]  {'Date First Available': 'August 2, 2014', 'Ma...  B00MCW7G9M            None
1            All Electronics                      Ce-H22B12-S1 4Kx2K Hdmi 4Port             5.0              1             [UPC: 662774021904, Weight: 0.600 lbs]                               [HDMI In - HDMI Out]    NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []             SIIG  [Electronics, Television & Video, Accessories,...  {'Product Dimensions': '0.83 x 4.17 x 2.05 inc...  B00YT6XQSE            None
2                  Computers  Digi-Tatoo Decal Skin Compatible With MacBook ...             4.5            246  [WARNING: Please IDENTIFY MODEL NUMBER on the ...                                                 []  19.99  [{'thumb': 'https://m.media-amazon.com/images/...  [{'title': 'AL 2Sides Video', 'url': 'https://...       Digi-Tatoo  [Electronics, Computers & Accessories, Laptop ...  {'Brand': 'Digi-Tatoo', 'Color': 'Fresh Marble...  B07SM135LS            None
3             AMAZON FASHION  NotoCity Compatible with Vivoactive 4 band 22m...             4.5            233  [☛NotoCity 22mm band is designed for Vivoactiv...                                                 []   9.99  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []         NotoCity  [Electronics, Wearable Technology, Clips, Arm ...  {'Date First Available': 'May 29, 2020', 'Manu...  B089CNGZCW            None
4  Cell Phones & Accessories             Motorola Droid X Essentials Combo Pack             3.8             64  [New Droid X Essentials Combo Pack, Exclusive ...  [all Genuine High Quality Motorola Made Access...  14.99  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []          Verizon  [Electronics, Computers & Accessories, Compute...  {'Product Dimensions': '11.6 x 6.9 x 3.1 inche...  B004E2Z88O            None
5          Sports & Outdoors  Raymarine Wi-Fish DownVision Blackbox Sonar wi...             3.5             25  [Black box Wi-Fi CHIRP DownVision sonar module...  [Transform your smartphone into a powerful CHI...    NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []        Raymarine  [Electronics, Car & Vehicle Electronics, Marin...  {'Item Package Dimensions L x W x H': '9.3 x 8...  B00TX536EK            None
6  Cell Phones & Accessories  QGHXO Band for Garmin Vivofit 4, Soft Silicone...             4.4            707  [Personalized Your Garmin Vivofit 4 Activity T...  [Compatibility, Custom designed for your preci...  14.89  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []            QGHXO  [Electronics, Wearable Technology, Arm & Wrist...  {'Package Dimensions': '6.85 x 4.37 x 1.1 inch...  B07BJ7ZZL7            None
7    Industrial & Scientific  Protech iPhone 4 microscope 60X Lens with illu...             3.8              6  [iPhone 4 Microscope with White 2-LED and Dete...  [This accessory will convert your iPhone 4 int...    NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []          ProTech  [Electronics, Camera & Photo, Binoculars & Sco...  {'Light Source Type': 'LED', 'Color': 'Blue,Wh...  B005G99O2U            None
8                  Computers  MOSISO Plastic Hard Shell Case & Keyboard Cove...             5.0              2                                                 []                                                 []    NaN  [{'thumb': 'https://m.media-amazon.com/images/...                                                 []           MOSISO  [Electronics, Headphones, Earbuds & Accessorie...  {'Brand': 'MOSISO', 'Item Weight': '8 ounces',...  B01MCZP7RF            None
9                        NaN  Fishfinder, Depth Finder Poly Sun Cover for 3"...             4.4             86  [Made of poly material, Available in black, Dr...  [Affordable and convenient way to cover your s...  10.99  [{'thumb': 'https://m.media-amazon.com/images/...  [{'title': 'Unboxing Gamin Vivid ', 'url': 'ht...  Westlake Market  [Electronics, Car & Vehicle Electronics, Marin...  {'Item Package Dimensions L x W x H': '7.32 x ...  B00R6R82HS            None

In [13]:
import pandas as pd

item_metadata_df['price'] = pd.to_numeric(item_metadata_df['price'], errors='coerce')

none_price_products = item_metadata_df[item_metadata_df['price'].isna()][['title', 'price']]

valid_price_products = item_metadata_df[item_metadata_df['price'].notna()][['title', 'price']]

print(f'products with no valid price listed (total: {len(none_price_products)})')

for i, row in enumerate(none_price_products.itertuples(index=False), start = 1):
    print(f'{i}. {row.title} - Price: {row.price}')

print(f'producs with valid price listed (total: {len(valid_price_products)})')
for i, row in enumerate(valid_price_products.itertuples(index=False), start = 1):
    print(f'{i}. {row.title} - Price {row.price}')

products with no valid price listed (total: 56)
1. FS-1051 FATSHARK TELEPORTER V3 HEADSET - Price: nan
2. Ce-H22B12-S1 4Kx2K Hdmi 4Port - Price: nan
3. Raymarine Wi-Fish DownVision Blackbox Sonar with Wi-Fi - Price: nan
4. Protech iPhone 4 microscope 60X Lens with illumination Led - Price: nan
5. MOSISO Plastic Hard Shell Case & Keyboard Cover Compatible MacBook Air 11 Inch (Models: A1370 & A1465), Transparent Black - Price: nan
6. Network Magic 4.0 - Price: nan
7. Dock Audio Extender Adapter Converter Cable for iPod iPhone 4 4S iPhone 5 5S iPad, Samsung & Other Smart Phones - Price: nan
8. NANW Bands Compatible with Fitbit Versa/Versa 2/Versa Lite Small Large, Soft Silicone Replacement Band for Versa/Versa 2, Air Hole Wristband Strap for Women Men - Price: nan
9. eForCity Leather Case with Stand for 7-Inch Samsung Galaxy Tab 2, White/Black Zebra (PSAMGLXTLC26) - Price: nan
10. KEiiD PC Computer Speaker Compact Bluetooth Stereo System with Aluminum Housing for Laptop Desktop PC Gaming Computers, Unique Touch Controller, Built-in Bluetooth 5.0 Receiver for Wireless Streaming - Price: nan
11. WD Scorpio Blue 320GB Mobile SATA Hard Drive - Price: nan
12. Leather Case for Cp S6/S7C - Price: nan
13. Nippon Audiodrift 6" 2-Way Speaker 4ohm 130w Max 14.25in. x 7.25in. x 3.25in. - Price: nan
14. Stanton STR8-100 Direct-Drive Digital Turntable with Straight Tone Arm (Discontinued by Manufacturer) - Price: nan
15. HTC Vivid Black/Blue Perforated Cover - Price: nan
16. Street Guardian SGGCX2PRO+ Dash Camera with GPS, CPL & 32GB MicroSD Card - Price: nan
17. SOONORY 2-Pack Sport Bands Compatible with Fitbit Charge 4 Bands, Large Small Man Woman Silicone Breathable Strap Replacement Wristbands with Air Holes for Fit Charge 4 / Charge 3 Smart Watch - Price: nan
18. MXditect EB166 Headphones with Mic Stereo Earphones for iOS Android Windows System, Black - Price: nan
19. Die-cut Vinyl decal sticker Snow White Holding an apple Compatible with Macbook Laptop Car window - Price: nan
20. Simplistex (TM) - Adjustable Folding Laptop Computer Stand - USB Fan Cooled - Silver - 2 Year Warranty - Price: nan
21. Brand New - Price: nan
22. Android 10.0 Car Stereo Radio Player GPS Navigation 9 Inch Touch Screen Head Unit WiFi Bluetooth Backup Camera DVR OBD2 TPMS for BMW E90 E91 E92 E93 325 (M400 4+64G) - Price: nan
23. HOSONGIN 1/4 Inch Female to 3.5mm TRS Male Adapter, Quarter 1/4" Inch 6.35mm Jack Female to 3.5mm 1/8" Inch TRS Plug Male Stereo Audio Adapter Gold Plated Pure Copper, Blue, 1 Pack - Price: nan
24. C2G 27385 Network Installation Tool Kit, TAA Compliant - Price: nan
25. Hosa Cable SKT450 Speakon to Banana Plug Speaker Cable - 50 Foot - Price: nan
26. VFENG Premium 4-in-1 3M Full Body Skin Sticker Decals, Decorative Protective Skin for Microsoft Surface Book 3 13.5 Inch 13'' 2020+ (Core i5 Version) - Gray - Price: nan
27. IU3D Low Noise DC 24V 0.12A 4010 Brushless Fan Cooler 40mm x 40mm x 10mm Cooling Fan. (2PCS -24V) - Price: nan
28. 1X (No Bluetooth) Eaglewireless Replacement Touch Stylus S Pen Pencil + 5 Replacement Tips and Sim Tray Ejector Pin for Samsung Galaxy Note 20 | Galaxy Note 20 Ultra 5G-Black (Bronze) - Price: nan
29. Dell Inspiron 17-5755 Laptop: AMD Quad-Core A8-7410U | 2TB | 12GB | 17.3" (1600x900) | DVD-RW | Windows 8.1 Upgradable to Win 10| Backlit Keyboard - Black /Silver (Certified Refurbished) - Price: nan
30. Superheadz Golden Half Black Mountain 35mm Film Camera - Price: nan
31. GOCOM GD900 Two Way Radio Long Range Rechargeable Walkie Talkies, Programmable Digital & Analog Radio for Adult, for Business Commercial Walkie Talkie - Price: nan
32. Bluetooth Earbuds Wireless Active Noise Canceling Headphones in-Ear Earphones with 4 Mics for Sports, Enhanced Deep Bass, 30Hrs Playtime, IPX8 Waterproof, Touch Control, USB-C Quick Charging Case - Price: nan
33. UIHY USB DATA cables 10Ft/3M Fabric Braided Sync Cable Charger Cord For iphone6 iphone6plus iPhone 5/iphone5s/iphone5c - Price: nan
34. 1.2m Brand new Replacement Cable for Sennheiser HD25 HD 25-1 HD25-1 II headphones - Price: nan
35. Cell Phone Car Mount, Magnetic, Universal, Black - Price: nan
36. 4K HDMI Cable 30 Foot - CAIVOV Ultra High Speed 24Gbps HDMI 2.0 Cable - 24AWG Nylon Braided HDMI Cord - 4K 60hz, HDR, 3D, 2160P, 1080P, Compatible UHD TV, Blu-ray, Xbox, PS4/3, PC, Fire TV - 30 feet - Price: nan
37. 3.5 mm Splitter, MillSO TRS 3.5mm Headphone Splitter Y Jack Audio Splitter, 3-Pole Gold Plated Male to Dual Female Compatible for Earphones, Speakers, Mobile Phones -30CM/11.8 inch - Price: nan
38. Toshiba TY-WSB600 2.1 Channel Bluetooth Soundbar TV Speaker: Sound Bar with Wireless Subwoofer, HDMI Arc with CEC, Optical, Coaxial, Aux and USB Inputs & Remote Control - Price: nan
39. 120mm Aluminum Fan Filter Grills w/ Mounting Screws, Black (2-Pack) - Price: nan
40. BENTOBEN iPad 9th Generation Case, iPad 8th Generation Case, iPad 7th Gen Case,iPad 10.2 Case,3 in 1 Heavy Duty Rugged Shockproof Kickstand Hybrid Bumper Protective Girl Women Boy Cover,Rainbow Design - Price: nan
41. Bolkin Kindle Fire HDX 8.9" Case Cover (Black) - Price: nan
42. Bluetooth Audio Speaker Power Amplifier - Portable Dual Channel Surround Sound Stereo Receiver - for Amplified Subwoofer Speakers, DVD, MP3, iPhone, Computer, Theater Via 3.5mm RCA - Pyle PCA4BT (Renewed) - Price: nan
43. Cable Clips with Strong Self-Adhesive, XIAOXI Cord Organizer Cable Management Organizing Cords Wire for Car, Home and Office - 20 Pcs (Clear) - Price: nan
44. 2020 Newest ASUS VivoBook 15.6" FHD Laptop Computer, AMD Ryzen 5 3500U up to 3.7GHz, Radeon RX Vega HDMI WiFi Bluetooth USB-C Windows 10 w/ CUE Accessories (12GB DDR4, 512GB SSD) - Price: nan
45. Fomito EW-78D 72mm Lens Hood for Canon EF-S 18-200mm f/3.4-5.6 is, 28-200mm f/3.4-5.6 USM, 28-200mm f/3.4-5.6 Lens(for Canon EW-78D Replacement) - Price: nan
46. Acer Aspire High Performance 15.6 inch HD Laptop PC, Intel Core i5-7200U Dual-Core, 6GB RAM, 128GB SSD (boot) + 1TB HDD, Bluetooth, WIFI, Windows 10 Home - Price: nan
47. Security Camera Cable 78inches, Pre-Made All-in-One BNC Extension Wire Cord for CCTV Camera - Price: nan
48. Gikfun Photoresistor GL5537 GL5528 LDR for Arduino EK1033 - Price: nan
49. Lenovo Tab 4 8 Case, ACdream Premium PU Folio Leather Tablet Case for Lenovo Tab4 8 Tablet(2017 Version), Black - Price: nan
50. AC to DC Charger with 6 Feet (2 Meter) Long Cord for NABi 2 II NABI2-NV7A NABI2-NVA (NABI-DC) - Price: nan
51. Desk Clamp Mount Suspension Arm Stand Holder for Mevo Live Event Camera by Livestream(1st Generation Only) - Price: nan
52. AirClassics Flight Bag | ASA-BAG-FLT-1 - Price: nan
53. AUGUR Travel Laptop Backpack - Price: nan
54. 128MB TF Card Flash Memory Card TF Card +Adapter (1pcs) - Price: nan
55. SSV Works Polaris Ranger XP9 900 2012-up and Fullsize Ranger 2015-up XP 900 Under the Seat Subwoofer Enclosure designed for 10" Speaker - Price: nan
56. YEELE 6x4ft Galaxy Backdrop Purple Night Sky in Deep Space of Universe Photography Backdrop Sci-fi Events Space Theme Birthday Decoration Kids Adults Artistic Portrait Photoshoot Studio Props - Price: nan
producs with valid price listed (total: 44)
1. Digi-Tatoo Decal Skin Compatible With MacBook Pro 13 inch (Model A2338/ A2289/ A2251) - Protective and Decorative Full Body Laptop Skin Decal Sticker, Anti-Scratch Vinly Skin Sticker Wrap [Fresh Marble] - Price 19.99
2. NotoCity Compatible with Vivoactive 4 band 22mm Quick Release Silicone Bands/Garmin Darth Vader/First Avenger/Polar Vantage Smartwatch Sport Breathable Strap Replacement for Gear S3 Classic Watchband - Price 9.99
3. Motorola Droid X Essentials Combo Pack - Price 14.99
4. QGHXO Band for Garmin Vivofit 4, Soft Silicone Replacement Watch Band Strap for Garmin Vivofit 4 Activity Tracker, Small, Large, Ten Colors (5PCS Bands-Girl, Large) - Price 14.89
5. Fishfinder, Depth Finder Poly Sun Cover for 3" - 4" Models - Protects Your Screen from Sun / Weather Damage - Price 10.99
6. Novelty Cute Cartoon USB 2.0 Flash Drive Data Storage Memory Stick Cartoon USB Stick Pendrive Gift (16GB, Camera Black) - Price 8.98
7. ANNKE 4K 16CH Security DVR Recorder with Human & Vehicle Detection and (16) 8MP Outdoor Bullet Cameras with IP67 Weatherproof, 100ft Night Vision with EXIR, Email Alert, NO Hard Drive - Price 909.99
8. BIPRA U3 2.5 inch USB 3.0 NTFS Portable External Hard Drive - White (250GB) - Price 98.49
9. Outer Space Planets Stickers(50Pcs),Planetary Systems Waterproof Vinyl Water Bottle Stickers for Teens Girls Adults Kids,Laptop Car Cup Computer Guitar Skateboard Luggage Phone Aesthetic Stickers Pack - Price 3.99
10. Gateway 15.6" FHD Ultra Slim Budget Notebook, Intel Pentium Processor(4-Core, up to 3.1 GHz), 4GB RAM, 128GB Storage, Precision Touchpad, HDMI, Type-C Windows 10S, Microsoft 365 1 Year, Charcoal Black - Price 189.99
11. VILTROX 24mm F1.8 f/1.8 FE Full-Frame Wide-Angle Prime Autofocus Lens for Sony E-Mount Camera a7R4 A7III A7S2 A5100 A6600 A6500 A6400 A6300 A6000 A7RIV A7RIII A7SIII A7III A7RII A7II A7S A7R A7 - Price 379.0
12. Polaroid Originals Now Viewfinder i-Type Instant Camera (White) Bundle with Color and B and W Instant Film and Reusable Vintage Photo Accessory (4 Items) - Price 179.99
13. NVIDIA NVS 310 by PNY 1 GB DDR3 PCI Express Gen 2 x16 DisplayPort 1.2 Multi-Display Professional Graphics Board, VCNVS310DP-PB (Renewed) - Price 34.98
14. luo Cherry MX RGB Switch Mute Pink Switch Mute Gray Switch Genuine German Cherry Switch (10PCS, Cherry RGB Mute Gray Switch) - Price 13.99
15. AntennaMastsRus - Made in USA - 4 Inch Black Aluminum Antenna is Compatible with Audi Allroad (2001-2005) - Price 22.99
16. HP Elitebook 8560W New Replacement LCD Screen for Laptop LED HD Matte - Price 63.33
17. May Chen Compatible with MacBook Pro 16 inch Case 2020 2019 Release A2141 with Touch Bar&Touch ID, Plastic Hard Shell Case with Keyboard Cover + Screen Protector, Abstract Leaves - Price 26.99
18. Wenlaty Case Compatible with iPad 9th /8th /7th Generation Case(2021/2020/2019), Full Body Protective with Pencil Holder, Designed for iPad 10.2 Inch, Auto Sleep/Wake Cover, Sky Blue - Price 19.99
19. Ares Vision Universal mounting CCTV Security Camera Wall Junction Box Bracket with Hidden Compartment (1 Pack, Wall Dome) - Price 13.99
20. Centon Electronics Flash Memory Card (S1-SDHU1-32G) - Price 8.99
21. Galaxy Tab A 10.1 Case 2019 - Techcircle Slim PU Leather Multiple Angle Stand Case with Card Slots Shockproof Cover for Samsung Galaxy Tab A 10.1 Inch Tablet SM-T510/T515 2019 Release, Purple Owl - Price 17.99
22. PNY 1TB PRO Elite Class 10 U3 V30 microSDXC Flash Memory Card - 100MB/s, Class 10, U3, V30, A2, 4K UHD, Full HD, UHS-I, micro SD - Price 109.99
23. LENTION USB C Docking Station, 10 Gbps USB C&USB A Ports, 4K 60Hz HDMI, 100W PD, Ethernet, Card Reader, USB 3.0, AUX, USB C Dock for MacBook/Surface, More, Stable Driver USB C Hub(CB-D65, Space Gray) - Price 89.99
24. JBL FLIP 5 - Waterproof Portable Bluetooth Speaker Made from 100% Recycled Plastic - Blue (Renewed) - Price 79.9
25. AvimaBasics Ear Buds, Spare Kit Earloops Buds Compatible with Plantronics WH500 CS540 W440 Savi W740 - Includes: 3 Earloop, 3 Eartips Guarantee! (1 Pack) - Price 9.99
26. Compatible with Ford Explorer 2006 2007 2008 2009 2010 Double DIN Stereo Harness Radio Install Dash Kit Package - Price 27.99
27. 10-Pack Replacement Clamp Bluetooth Ear Hook Loop Clip Replacement - Set Of 5 Black SMALL Clamps + 5 Pack Black Large Clamps Shape Clear Hook for Samsung, Motorola, LG & Other Bluetooth Headsets - Price 3.49
28. Cable Raceways - Floor Cord Protector Cable Shield Cord Cover PVC Floor Wire Protect - Price 17.87
29. MHYALUDO Silicone Print Case Cover for Apple Airpods Pro 2nd Generation 2022 & 1st Generation 2019 Charging Case, Soft Earpods Case with keychain for Women with Airpods Pro Charging Case-White Leopard - Price 10.99
30. iCasso Compatible with MacBook Pro 13 Inch Case 2016-2020 Release A2338 M1 A2251 A2289 A2159 A1989 A1706 A1708, Hard Plastic Case, Sleeve, Screen Protector, Keyboard Cover & Dust Plug - Serenity Blue - Price 27.99
31. SUPCASE UB Pro Series Case for iPad Pro 12.9 inch for 2020 Release only, Support Apple Pencil Charging with Built-in Screen Protector Full-Body Rugged Kickstand Protective Case (Black) - Price 27.99
32. Nurse Stickers for Water Bottles and Laptop, Nursing Stickers for Nurse Students, Nurses, and Healthcare Workers, Waterproof, Reusable, No Residue Vinyl Decal Perfect Nurse Gift (108 Designs) - Price 8.99
33. 13-15.6 Inch Laptop Sleeve Case Women Men Shoulder Bag Briefcase Messenger Bag Portable Handbag - Price 14.88
34. 3pcs 4 Wire 2 Phase DC Micro Stepper Motor Step Height 10mm with Output Gear - Price 6.99
35. CoBak Case for Kindle Paperwhite - All New PU Leather Cover with Auto Sleep Wake Feature for Kindle Paperwhite Signature Edition and Kindle Paperwhite 11th Generation 2021 Released - Price 18.95
36. GIGABYTE AERO 16 XE5-16" 4K/UHD+ Samsung AMOLED, Intel Core i7-12700H, NVIDIA GeForce RTX 3070 Ti Laptop GPU 8GB GDDR6, 32GB DDR5 RAM, 2TB SSD,Win11 Pro Laptop (AERO 16 XE5-73US948HP) - Price 1749.0
37. GGS Swivi HD DSLR LCD Universal Foldable Viewfinder Version II with 3.0X Magnification - Price 149.0
38. Kate 10x6.5ft Dark Wood Photo Backdrop for Photographers Horizontal Wooden Texture Floor Backgrounds for Studio Photo Props - Price 78.0
39. Plugable USB C to HDMI Adapter 4K 30Hz, Thunderbolt 3 to HDMI Adapter Compatible with MacBook Pro, Windows, Chromebooks, 2018+ iPad Pro, Dell XPS, Thunderbolt 3 Ports and More - Price 21.95
40. Adafruit FTDI Serial TTL-232 USB Cable [ADA70] - Price 24.63
41. 8x8ft Pink Rose Flower Theme Photography Backdrops 3D Pink Floral Newborn Kids Wedding Bridal Shower Photo Background Mother's Day Anniversary Ceremony Couple Photo Props Cake Table Banner - Price 38.9
42. LaCie Rugged All-Terrain Safe 500 GB USB 2.0/FireWire 800 Portable External Hard Drive 301491 - Price 146.99
43. Monsoon G1/4" to 1/2" ID, 3/4" OD Chain Gun Compression Fitting for Soft Tubing, Chrome, 4-Pack - Price 25.71
44. Aruba Instant On AP11 2x2 WiFi Access Point | US Model | Power Source Included (R3J21A) - Price 109.99

In [ ]:
def get_product(product_title):
    try:
        price = item_metadata_df.loc[item_metadata_df['title'] == product_title, 'price'].values[0]
        if pd.isna(price):
            return 'no valid price listed'
    except IndexError:
        return 0